### ISSUE TITLE
Basic funtionality doesn't work

### ISSUE THREAD

**Issue by Ma100Dev** [bahmutov/json-server-reset#80]
- version: "json-server-reset": "^1.3.3",
- platform: Pop!_OS 22.04 LTS Linux with Node v16.16.0
- steps to reproduce
    - ```npm i json-server-reset```
    - [add reset to code](https://github.com/Ma100Dev/anecdotes-cicd/blob/d2bc417bd18a0e9b4c06288bf25e164fdf3b3a0d/backend/server.js#L60)
    - use HTTPie example: ```http POST :3000/reset todos:=[]```
- expected behavior
    - database resets to given value
- actual behavior
    - gives error and does not reset
    - console output:
```
resetting database
TypeError: Cannot read properties of undefined (reading 'setState')
    at jsonServerReset (/home/user/Documents/anecdotes-cicd/node_modules/json-server-reset/src/index.js:15:16)
    at Layer.handle [as handle_request] (/home/user/Documents/anecdotes-cicd/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/user/Documents/anecdotes-cicd/node_modules/express/lib/router/index.js:328:13)
    at /home/user/Documents/anecdotes-cicd/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/user/Documents/anecdotes-cicd/node_modules/express/lib/router/index.js:346:12)
    at next (/home/user/Documents/anecdotes-cicd/node_modules/express/lib/router/index.js:280:10)
    at expressInit (/home/user/Documents/anecdotes-cicd/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/user/Documents/anecdotes-cicd/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/user/Documents/anecdotes-cicd/node_modules/express/lib/router/index.js:328:13)
    at /home/user/Documents/anecdotes-cicd/node_modules/express/lib/router/index.js:286:9
```
- repository with all my code: https://github.com/Ma100Dev/anecdotes-cicd

**Comment by bahmutov** [comment]
Fixed
